module gitlab.com/circulohealth/sonar/backend

go 1.16

// Used to update go_repositories.bzl with Gazelle
// Automatically generated by running //tools/update-deps
replace github.com/circulohealth/sonar-backend/packages/cloud => ./packages/cloud

replace github.com/circulohealth/sonar-backend/packages/cms => ./packages/cms

replace github.com/circulohealth/sonar-backend/packages/common => ./packages/common

replace github.com/circulohealth/sonar-backend/packages/companulo => ./packages/companulo

replace github.com/circulohealth/sonar-backend/packages/forms => ./packages/forms

replace github.com/circulohealth/sonar-backend/packages/global => ./packages/global

replace github.com/circulohealth/sonar-backend/packages/member => ./packages/member

replace github.com/circulohealth/sonar-backend/packages/pearls => ./packages/pearls

replace github.com/circulohealth/sonar-backend/packages/router => ./packages/router

replace github.com/circulohealth/sonar-backend/packages/search => ./packages/search

replace github.com/circulohealth/sonar-backend/packages/support => ./packages/support

replace github.com/circulohealth/sonar-backend/packages/users => ./packages/users

replace github.com/circulohealth/sonar-backend/packages/feature_flags => ./packages/feature_flags

replace github.com/circulohealth/sonar-backend/packages/patient => ./packages/patient

require (
	code.rocketnine.space/tslocum/godoc-static v0.2.1 // indirect
	github.com/DATA-DOG/go-sqlmock v1.5.0
	github.com/aws/aws-lambda-go v1.28.0
	github.com/aws/aws-sdk-go v1.40.20
	github.com/circulohealth/sonar-backend/packages/cloud v0.0.0-00010101000000-000000000000
	github.com/circulohealth/sonar-backend/packages/common v0.0.0-00010101000000-000000000000
	github.com/circulohealth/sonar-backend/packages/feature_flags v0.0.0-00010101000000-000000000000
	github.com/circulohealth/sonar-backend/packages/forms v0.0.0-00010101000000-000000000000
	github.com/circulohealth/sonar-backend/packages/global v0.0.0-00010101000000-000000000000
	github.com/circulohealth/sonar-backend/packages/patient v0.0.0-00010101000000-000000000000
	github.com/circulohealth/sonar-backend/packages/router v0.0.0-00010101000000-000000000000
	github.com/circulohealth/sonar-backend/packages/support v0.0.0-00010101000000-000000000000
	github.com/circulohealth/sonar-backend/packages/users v0.0.0-00010101000000-000000000000
	github.com/go-playground/universal-translator v0.17.0 // indirect
	github.com/go-playground/validator v9.31.0+incompatible
	github.com/golang-jwt/jwt v3.2.2+incompatible
	github.com/google/uuid v1.0.0
	github.com/jackc/pgx/v4 v4.14.1 // indirect
	github.com/leodido/go-urn v1.2.1 // indirect
	github.com/lestrrat-go/iter v1.0.1
	github.com/lestrrat-go/jwx v1.2.6
	github.com/lib/pq v1.10.2 // indirect
	github.com/sethvargo/go-password v0.2.0
	github.com/stretchr/testify v1.7.0
	go.uber.org/atomic v1.9.0 // indirect
	go.uber.org/multierr v1.7.0 // indirect
	go.uber.org/zap v1.20.0
	golang.org/x/crypto v0.0.0-20220126234351-aa10faf2a1f8 // indirect
	gopkg.in/go-playground/assert.v1 v1.2.1 // indirect
	gorm.io/driver/postgres v1.2.3
	gorm.io/gorm v1.22.5
)
