// Code generated by mockery v2.9.4. DO NOT EDIT.

package iface

import (
	model "github.com/circulohealth/sonar-backend/packages/users/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// MockExternalUserOrganization is an autogenerated mock type for the ExternalUserOrganization type
type MockExternalUserOrganization struct {
	mock.Mock
}

// Find provides a mock function with given fields: id
func (_m *MockExternalUserOrganization) Find(id int) (*model.ExternalUserOrganization, error) {
	ret := _m.Called(id)

	var r0 *model.ExternalUserOrganization
	if rf, ok := ret.Get(0).(func(int) *model.ExternalUserOrganization); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ExternalUserOrganization)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *MockExternalUserOrganization) FindAll() ([]*model.ExternalUserOrganization, error) {
	ret := _m.Called()

	var r0 []*model.ExternalUserOrganization
	if rf, ok := ret.Get(0).(func() []*model.ExternalUserOrganization); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ExternalUserOrganization)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: record
func (_m *MockExternalUserOrganization) Insert(record *ExternalUserOrganizationInsertInput) (*model.ExternalUserOrganization, error) {
	ret := _m.Called(record)

	var r0 *model.ExternalUserOrganization
	if rf, ok := ret.Get(0).(func(*ExternalUserOrganizationInsertInput) *model.ExternalUserOrganization); ok {
		r0 = rf(record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ExternalUserOrganization)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ExternalUserOrganizationInsertInput) error); ok {
		r1 = rf(record)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: dm
func (_m *MockExternalUserOrganization) Update(dm *model.ExternalUserOrganization) (*model.ExternalUserOrganization, error) {
	ret := _m.Called(dm)

	var r0 *model.ExternalUserOrganization
	if rf, ok := ret.Get(0).(func(*model.ExternalUserOrganization) *model.ExternalUserOrganization); ok {
		r0 = rf(dm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ExternalUserOrganization)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ExternalUserOrganization) error); ok {
		r1 = rf(dm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
