CREATE TABLE IF NOT EXISTS patient (
  patient_id uuid DEFAULT gen_random_uuid(),
  medicaid_id VARCHAR(250) NULL,
  first_name VARCHAR(250) NOT NULL,
  middle_name VARCHAR(250) NULL,
  last_name VARCHAR(250) NOT NULL,
  suffix VARCHAR(250) NULL,
  date_of_birth DATE DEFAULT '1/1/1900' NULL,
  primary_language VARCHAR(250) NULL,
  preferred_gender VARCHAR(250) NULL,
  email_address VARCHAR(250) NOT NULL,
  home_phone VARCHAR(250) NULL,
  home_living_arrangement VARCHAR(250) NULL,
  home_address_1 VARCHAR(250) NOT NULL,
  home_address_2 VARCHAR(250) NULL,
  home_city VARCHAR(250) NOT NULL,
  home_county VARCHAR(250) DEFAULT 'Unknown' NOT NULL,
  home_state VARCHAR(250) NOT NULL,
  home_zip VARCHAR(250) NOT NULL,
  signed_circulo_consent_form BOOLEAN NOT NULL DEFAULT FALSE,
  circulo_consent_form_link VARCHAR(250) NULL,
  signed_stationmd_consent_form BOOLEAN NOT NULL DEFAULT FALSE,
  stationmd_consent_form_link VARCHAR(250) NULL,
  completed_go_sheet BOOLEAN NOT NULL DEFAULT FALSE,
  marked_as_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_timestamp TIMESTAMP without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
  last_modified_timestamp TIMESTAMP without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
  PRIMARY KEY (patient_id)
);
