// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EventPublisher is an autogenerated mock type for the EventPublisher type
type EventPublisher struct {
	mock.Mock
}

// PublishConnectionCreatedEvent provides a mock function with given fields: userId, service
func (_m *EventPublisher) PublishConnectionCreatedEvent(userId string, service string) error {
	ret := _m.Called(userId, service)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userId, service)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
