// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	events "github.com/aws/aws-lambda-go/events"

	mock "github.com/stretchr/testify/mock"
)

// IteratorHandler is an autogenerated mock type for the IteratorHandler type
type IteratorHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: message
func (_m *IteratorHandler) Execute(message events.SQSMessage) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(events.SQSMessage) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
