// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	dto "github.com/circulohealth/sonar-backend/packages/common/connection/dto"

	mock "github.com/stretchr/testify/mock"
)

// OnlineChecker is an autogenerated mock type for the OnlineChecker type
type OnlineChecker struct {
	mock.Mock
}

// IsUserOnline provides a mock function with given fields: userID
func (_m *OnlineChecker) IsUserOnline(userID string) (dto.UserOnlineStatus, error) {
	ret := _m.Called(userID)

	var r0 dto.UserOnlineStatus
	if rf, ok := ret.Get(0).(func(string) dto.UserOnlineStatus); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(dto.UserOnlineStatus)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
